#!/bin/bash

info() {
  echo -e "\e[32m$*\e[0m"
}

warning () {
  echo -e "\e[31m$*\e[0m";
}

fatal() {
  warning $*;
  exit -1;
}

debug () {
  [ -n "$enabledebug" ] && echo -e "\e[33m$*\e[0m"
}

usage () {
  warning "usage:";
  info " $0 hdfs <prop> <value>";
}

hdfs () {
  site=$HADOOP_CONF_DIR/hdfs-site.xml
  [ -z "$HADOOP_CONF_DIR" ] && {
    site=$HADOOP_HOME/hdfs-site.xml
  } && [ -z "$HADOOP_HOME" ] && {
    fatal "HADOOP_CONF_DIR or HADOOP_HOME not defined.";
  }
  k=$(grep -n "<name>$1</name>" $site)
  debug $k
  if [ -n "$k" ] ;then
    kv=$(grep -o -z "<name>$1</name>\s*<value>[^<>]*</value>" $site)
    v=$(echo $kv|grep value|awk -F\> '{print $4}'|awk -F\< '{print $1}')
    debug $kv
    debug $v
    if [ $# -eq 1 ] ;then
      info "$1 : $v"
    else
      sed -i "/^\s*<name>$1<\/name>\s*$/{\$!{N;s/^\(\s*<name>dfs.replication<\/name>\s*\n\s*<value>\)[^<>]*\(<\/value>\)\$/\1$2\2/;ty;P;D;:y}}" $site
      [ $? -eq 0 ] && info "[mod] $1 = $v -> $2"
    fi
  else
    if [ $# -eq 2 ] ;then
      sed -i "/<configuration>/a\ \ <property>\n    <name>$1<\/name>\n    <value>$2<\/value>\n  <\/property>" $site
      [ $? -eq 0 ] && info "[add] $1 = $2"
    else
      warning "property $1 not found."
    fi
  fi
}

for c in $* ;do
  case $c in
    -d)
      enabledebug=true;;
    *)
      if [ -z "$cmd" ] ;then
        cmd=$c
      else
        arg+=$c
      fi
      ;;
  esac
done

debug $cmd $arg
case $cmd in
  hdfs) hdfs $arg;;
  *) usage;;
esac
